tables:
  samples:
    shakespeare:
      type: public_table
      params:
        properties:
          tableReference:
            projectId: bigquery-public-data
            datasetId: samples
            tableId: shakespeare
  pypi:
    file_downloads:
      type: public_table
      params:
        properties:
          timePartitioning:
            field: timestamp
          tableReference:
            projectId: bigquery-public-data
            datasetId: pypi
            tableId: file_downloads
