logging:
  type: colored
  level: DEBUG
  message_format: '%(asctime)s %(name)s:%(lineno)d %(levelname)s %(message)s'
  timestamp_format: '%m-%d %H:%M:%S'
  loggers:
    gcsfs: INFO
    google.auth: INFO
    google.cloud.bigquery.opentelemetry_tracing: WARNING
    asyncio: INFO
    urllib3: INFO
